### PR TITLE
fix: nested object validation

### PR DESCRIPTION
**Pull request by purepear**
# Description

This fixes a regression which allows an object field validation to pass even if it has a nested object field which validation fails.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] npm test
- [x] Locally tested

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by nicksnell** [comment]
We do include the compiled JS, I'm not sure exactly what we were doing that for any more - it doesn't need to be there as long as the published version includes the built artefacts (obvs!)

**Comment by purepear** [comment]
I don't think we include the compiled version.
https://github.com/mutt-forms/mutt-forms/blob/master/.gitignore#L12

**Comment by purepear** [comment]
But in general - we should not include it anyway

**Comment by alexrussell** [comment]
> I don't think we include the compiled version.
> https://github.com/mutt-forms/mutt-forms/blob/master/.gitignore#L12

Ahh I'm probably thing of m-f-v.

> But in general - we should not include it anyway

I agree in general - as Nick says, as long as it's in the distributed package it doesn't need to be in the repo. That said, it can help with non-final-version usage, but that's not exactly commonplace.

**Pull request merged**
