### PR TITLE
v2.3.1

### PR DESCRIPTION
**Pull request by purepear**

### CODE REVIEW

**Comment by alexrussell** [comment]
Is this based on #36?

**Comment by purepear** [comment]
yes

**Comment by alexrussell** [comment]
Then this could be a minor bump according to your PR desc there.

**Comment by purepear** [comment]
Yeah but it adds additional functionality, it's not bug fix or refactor

**Comment by purepear** [comment]
@alexrussell aaahhhh sorry
I confused this PR with the one in `mutt-forms-vue`
will change the version, you are correct

**Pull request merged**
